In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a[0],a[1])

1 2


In [7]:
b = np.array(([1,2,3,4],[6,7,8,9]))

In [8]:
print(b)

[[1 2 3 4]
 [6 7 8 9]]


In [9]:
print(b.shape)

(2, 4)


In [10]:
print(b[0,0],b[1,1])

1 7


In [ ]:
#Numpy Function

In [22]:
a = np.zeros((5,5))

In [23]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
 b = np.ones((5,6))

In [28]:
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
