In [37]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [38]:
df = pd.read_csv('homeprices.csv')

In [39]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
dtype: int64

In [40]:
df.head()

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         3   18  610000
3  3600         3   30  595000
4  4000         5    8  760000

In [41]:
reg  = linear_model.LinearRegression()

In [42]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [43]:
reg.predict([[2600,3,20]])

array([522772.68339768])

In [44]:
reg.coef_

array([  119.67905405, 13097.24903475, -4207.28764479])

In [45]:
256461.14864864887 + 119.67905405* 2600+13097.24903475*3+(-4207.28764479)*20

522772.6833870989

In [46]:
reg.intercept_

256461.14864864887

In [47]:
reg.predict([[4100,6,8]])

array([792070.46332046])